### ISSUE TITLE
Error message raised in snakemake-workflow-catalogue

### ISSUE THREAD

**Issue by franciscozorrilla** [snakemake/snakefmt#105] opened 2021-04-28 14:52 UTC
Hi, I searched for the [metaGEM](https://github.com/franciscozorrilla/metaGEM) workflow in the [snakemake catalogue](https://snakemake.github.io/snakemake-workflow-catalog/) and I see that the QC tab shows that my formatting is failing. Clicking on the failed formatting badge shows the following error message:

```
[ERROR] In file "/tmp/tmpaisj4fsi/franciscozorrilla-metaGEM-cc3d75a/Snakefile":  'NoParametersError: L519: In output definition.'
[INFO] In file "/tmp/tmpaisj4fsi/franciscozorrilla-metaGEM-cc3d75a/Snakefile":  1 file(s) raised parsing errors 🤕
```

Any idea what is going wrong?

Thanks,
Francisco

**Comment by mbhall88** [comment] 2021-04-29 01:16
Hi Francisco, it's a little hard without seeing the exact file you ran this on, but looking at the Snakefile in the repo you linked, it looks like https://github.com/franciscozorrilla/metaGEM/blob/b3f524dc79e5118c1796621d0be6771d0ce655f0/Snakefile#L577-L578 could be the cause. This is related to #104

**Comment by mbhall88** [comment] 2023-01-27 04:06
closing in favour of #104

**Closed by mbhall88** 2023-01-27 04:06 UTC
Labels: question
