### ISSUE TITLE
spaces added in f-strings

### ISSUE THREAD

**Issue by jbloom** [snakemake/snakefmt#224] opened 2024-04-11 13:40 UTC
`snakefmt` 0.10.0 re-formats f-strings that are originally like this:
```
print(f"{x=}")
```
to be like this:
```
print(f"{x =}")
```

I don't think this is intended, is it?

**Comment by mbhall88** [comment] 2024-04-11 23:28
This is essentially a duplicate of #220. I'll close this in favour of that issue and you can follow along there

**Closed by mbhall88** 2024-04-11 23:28 UTC
